C3-142 : Issue while create VM with Private Network
apporbit/libretto pull request #12
Opened 2017-03-08 06:32 UTC by avnish30jn

Jira Id

C3-142

**Problem**

Cannot create vm with networks other than 'VM Network'

**Solution**

Added support for adding the networks specified in the vm struct

**Testing** 

**Unit Testing**

Done. Tried to create vm with VMprivate-network, the vm was assigned with the VMprivate-network, and a local ip is assigned to the vm.

[root@localhost test]# go run vsphereclient.go
Vm created and is powered on
{"IPs":["10.10.24.209","fe80::72cd:ca68:a895:5ae0","fe80::8d39:b744:d6bd:9a0d"]}

2017-03-08 07:18 UTC, sjpotter commented
instead of 

func reconfigureNetworks(vm *VM) ([]types.BaseVirtualDeviceConfigSpec, error)

it should be 

func reconfigureNetworks(vm *VM) (types.BaseVirtualDeviceConfigSpec, error)

and you would append its result, so 

instead of

deviceChangeSpec, err := reconfigureNetworks(vm)

you would have something like

deviceChangeSpecs := []types.BaseVirtualDeviceConfigSpec{}
deviceChangeSpec, err := reconfigureNetworks(vm)
deviceChangeSpecs = append(deviceChangeSpecs, deviceChangeSpec)

2017-03-16 15:50 UTC, pankajtandon12 requested changes
LGTM. Minor comments.
Please test following scenarios as well with changes:
- Use Public Network
- Use both Private & Public Network

2017-03-16 15:50 UTC, pankajtandon12 commented on virtualmachine/vsphere/util.go
> +	// create ehternet card with the backing info
ethernet

2017-03-16 15:50 UTC, pankajtandon12 commented on virtualmachine/vsphere/util.go
> +	// connect to the newtork when the nic is connected to vm
network

2017-03-16 15:50 UTC, pankajtandon12 commented on virtualmachine/vsphere/util.go
> +// netowrks in the vm structure
networks

2017-03-27 02:38 UTC, avnish30jn commented
Tested with below scenarios

Use Public Network
Use both Private & Public Network
Use private network only

2017-03-28 03:22 UTC, pankajtandon12 approved these changes

2017-03-28 03:22 UTC, merged