MRPHS-2772 Adding support to fetch templates for a DC
apporbit/libretto pull request #29
Opened 2017-08-12 07:21 UTC by sumeetk-gem

[MRPHS-2772](https://apporbit.atlassian.net/browse/MRPHS-2772)

### Description:
get_template_vm_list call needs to return templates at the entire DC level (in addition to specific cluster level) for infra VM WFs

### Resolution:
Extending get_template_vm_list call to return templates at the entire DC level

### Order of reviewing
n/a

### Testing:

**Unit Testing:**
Tested enhancements to existing APIs and new APIs using c3ntry_client

2017-08-12 18:21 UTC, avnish30jn requested changes

2017-08-12 18:21 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +// GetVirtualMachines : Return the virtual machines in a cluster
GetVirtualMachines -> getVirtualMachines .

2017-08-12 18:21 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +		// Return templates for the whole datacenter
Is this comment correct ?

2017-08-12 18:21 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +		dcObj, err := vm.finder.Datacenter(vm.ctx, vm.Datacenter)
Should we use GetDatacenter func here ?

2017-08-21 06:44 UTC, sumeetk-gem commented on virtualmachine/vsphere/vm.go
> +		// Return templates for the whole datacenter
Since no cluster is specified we return templates in the entire DC.

2017-08-21 06:53 UTC, sumeetk-gem commented on virtualmachine/vsphere/vm.go
> +		dcObj, err := vm.finder.Datacenter(vm.ctx, vm.Datacenter)
I tried using it at first, but it returns *mo.Datacenter, which does not match the arg type of `getDcVMList()`

2017-08-21 09:04 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +		// Return templates for the whole datacenter
This should be 
```
// Return virtualmachines for the whole datacenter
```

2017-08-21 09:11 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +		dcObj, err := vm.finder.Datacenter(vm.ctx, vm.Datacenter)
This should work
```
dcMo, err := GetDatacenter(vm)
dc := object.Datacenter(vm.client.Client, dcMo.Reference())
```

2017-08-21 11:39 UTC, avnish30jn approved these changes
LGTM

2017-08-21 11:45 UTC, merged