Out of date govmomi being used in libretto.
apporbit/libretto pull request #3
Opened 2017-02-08 03:51 UTC by avnish30jn

**Problem**

Govmomi in libretto is out of date. Updating govmomi needs some code changes in libretto.

**Solution**

Changed the libretto code to work with govmomi, Context updated similar to govmomi, UnitNumber now returning reference, hence removing '&', Create disk takes one more parameter, datastore ManagedObjectReference, Conflicting int and int32

2017-02-14 07:27 UTC, pankajtandon12 requested changes
@avnish30jn Please find some review comments.
If not already, please ensure that corresponding changes are done for all instances of issue.

2017-02-14 07:27 UTC, pankajtandon12 commented on virtualmachine/vsphere/util.go
remove this empty line

2017-02-14 07:27 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +	"context"
move this up, along with rest of the standard library

2017-02-14 07:27 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +	v.Lease.HttpNfcLeaseProgress(v.Ctx, int32(p))
This change should be propagated to callers as well.
i.e.
func (v VMwareLease) HTTPNfcLeaseProgress(p int32) {

2017-02-14 07:27 UTC, pankajtandon12 commented on virtualmachine/vsphere/util.go
> +		return fmt.Errorf("Failed to retrieve datacenter: %s", err)
use `return err`, same as rest of the code. Assuming caller is expecting/handling that.
You can still print the user friendly failure message before returning.

2017-02-14 07:27 UTC, pankajtandon12 commented on virtualmachine/vsphere/util.go
> +	dsMo, err := findDatastore(vm, dcMo, vm.Datastores[0])
Missing error handling for vm.Datastores[0].
Is it assumed to be handle in caller? 
Generic: For all param validations, if it is assumed to be handle by caller, Add a comment to inform that explicitly.

2017-02-14 09:11 UTC, avnish30jn commented on virtualmachine/vsphere/util.go
This is corrected

2017-02-14 09:11 UTC, avnish30jn commented on virtualmachine/vsphere/util.go
> +		return fmt.Errorf("Failed to retrieve datacenter: %s", err)
This is corrected

2017-02-14 09:11 UTC, avnish30jn commented on virtualmachine/vsphere/util.go
> +	dsMo, err := findDatastore(vm, dcMo, vm.Datastores[0])
This is corrected

2017-02-14 09:11 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +	"context"
This is corrected

2017-02-14 09:11 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +	v.Lease.HttpNfcLeaseProgress(v.Ctx, int32(p))
This is corrected

2017-02-15 10:05 UTC, pankajtandon12 approved these changes

2017-02-15 17:11 UTC, merged