MRPHS-3065 Fixing issues with custom network selection in create_vms
apporbit/libretto pull request #32
Opened 2017-08-28 15:50 UTC by sumeetk-gem

[MRPHS-3065](https://apporbit.atlassian.net/browse/MRPHS-3065)

### Description:
When cloning from VM template to create new VM, we remove all network devices in the template and attach new ones of type 'e1000'. If the template has devices of different type, then they get new interface ids in the VM and are unable to connect to the network due to missing config files for the new identifiers.

### Resolution:
1. Changing default interface type to 'vmxnet3' for new interfaces (as per discussions)
2. Since user only has the capacity to select networks to be added to the new VM through AO but not interface type etc., editing existing devices in template with new network would retain their other properties including there types and identifiers. New approach to n/w configuration -
 a. If (number of networks mentioned by user) = (no. of devices in template), then edit template's devices in clone to be attached to n/ws entered by user.
 b. If (number of networks mentioned by user) > (no. of devices in template), then edit existing devices in order and add the pending as new ones
 c. If (number of networks mentioned by user) < (no. of devices in template), then edit existing devices in order and remove the excess ones.
3. `Network` property of VM object was a map. But, it is possible for a VM to have more than one device attached to the same n/w which won't be possible to represent in a map. Also, order of networks needs to be preserved. Changing type to `[]map[string]string`

### Order of reviewing
n/a

### Testing:

**Unit Testing:**
Tested various combinations of n/w configs using c3ntry_client

2017-08-28 20:52 UTC, arindam2 reviewed
Made a couple of observations. Please address them.

2017-08-28 20:52 UTC, arindam2 commented on virtualmachine/vsphere/util.go
> +			continue
I think `default: continue` is optional? It is equivalent to not specifying it.

2017-08-28 20:52 UTC, arindam2 commented on virtualmachine/vsphere/util.go
> +			nw, vm.Networks = vm.Networks[0], vm.Networks[1:]
This feels a little unreadable. The following feels easier to read:

    nws_len := len(vm.Networks)
    devs_len := len(devices)
    
    if devs_len < nws_len
      // generate all the remove specs here
      // on vm.Networks[devs_len:]
    end
    
    // generate all the edit specs on devices[0:devs_len] (or devices[0:devs_len-1] - check syntax)

There's also less garbage to collect.

2017-08-28 20:54 UTC, avnish30jn requested changes

2017-08-28 20:54 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +	Networks []map[string]string
update the description

2017-08-28 20:54 UTC, avnish30jn commented on virtualmachine/vsphere/util.go
> +			nw, vm.Networks = vm.Networks[0], vm.Networks[1:]
should we avoid modifying vm struct, it could be used somewhere ?

2017-08-29 10:12 UTC, avnish30jn approved these changes
LGTM

2017-08-29 10:13 UTC, merged