Create disk on different datstore in add volume operation
apporbit/libretto pull request #37
Opened 2017-10-04 14:38 UTC by avnish30jn

**Jira id**

**Problem**

Provision to create volume from different datastores.

**Solution**

Passed the datastore along with the disk properties and created a new volume using that datastore.

**Unit Testing**

In progress.

2017-10-10 09:55 UTC, pankajtandon12 requested changes
Please resolve conflict. Minor comment.

2017-10-10 09:55 UTC, pankajtandon12 commented on virtualmachine/vsphere/util.go
> +		if disk.Datastore == "" {
Please add explanatory comments that root-disk datastore will be used by-default.

2017-10-13 02:23 UTC, pankajtandon12 commented
@avnish30jn Please rebase and resolve code conflicts.

2017-10-23 06:27 UTC, avnish30jn commented
Rebase and resolved conflicts

2017-10-23 09:37 UTC, pankajtandon12 approved these changes
LGTM.

2017-10-23 10:13 UTC, merged