MRPHS-3404: Added dummy methods for new methods of VirtualMachine interface
apporbit/libretto pull request #41
Opened 2017-10-10 10:51 UTC by nirav1007

**Jira id**
[MRPHS-3404](https://apporbit.atlassian.net/browse/MRPHS-3404)

Problem
New methods have been added to VirtualMachine interface, thus dummy methods needs to be implemented in AWS/vm.go for build

Solution
Added dummy methods in vm.go

2017-10-10 11:43 UTC, pankajtandon12 requested changes
In Discussion.

2017-10-10 12:00 UTC, nirav1007 commented
Have removed declaration of AddDisk, RemoveDisk and Reset from VM Interface. But have kept added dummy methods in aws/vm.go as anyway it will have to be implemented.

2017-10-10 12:17 UTC, avnish30jn approved these changes
LGTM

2017-10-10 12:44 UTC, pankajtandon12 requested changes

2017-10-10 12:44 UTC, pankajtandon12 commented on virtualmachine/aws/vm.go
> +// AddDisk adds disk to instance
This code of dummy methods can be removed now. And added with implementation only.

2017-10-12 08:04 UTC, pankajtandon12 approved these changes
LGTM

2017-10-12 09:49 UTC, merged