Support for deleting the vm template
apporbit/libretto pull request #7
Opened 2017-02-17 04:03 UTC by avnish30jn

**Jira ID**
C3-103

**Problem**
No support for deleting the templates on vsphere cloud

**Solution**
Added support for deleting the template from vsphere cloud

**Testing**
  **Manual**
Tried deleting template that exist - Template Deleted
Tried deleting template that does not exist - Error message template does not exist

2017-02-17 10:11 UTC, pankajtandon12 requested changes
@avnish30jn 
Generic: Please add more comments. Code is not self-explanatory.

2017-02-17 10:11 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +
Please add function description.

2017-02-17 10:11 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +		template := createTemplateName(vm.Template, datastore)
Not sure in which PR, you are merging your createTemplateName() upstream.
Please test halo with these changes.

2017-02-17 10:11 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +			return fmt.Errorf("Error waiting for tast : %s", err)
"tast" -> "task"

2017-02-17 10:11 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +			templates = append(templates, template)
I think template name is suppose to be unique. In that case, there won't be more than one match for template specified (to-be-deleted).
Do we need templates []string in that case?

2017-02-17 11:08 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +		template := createTemplateName(vm.Template, datastore)
This is provided by libretto.

2017-02-17 11:11 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +			templates = append(templates, template)
Based on the value of flag UseLocalTemplates in vm struct the template may be uplaoded to all the datastores passed in. 

	// UseLocalTemplates is a flag to indicate whether a template should be uploaded on all
	// the datastores that were passed in.

2017-02-21 07:15 UTC, pankajtandon12 requested changes
@avnish30jn 
1. Try to mention comments as full sentence.
2. VM-template name generation will change, lead to change in this code. Open a JIra Ticket for that.

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +// Deletes the template created during vm Provisioning
->
  // DeleteTemple deletes the vm-template, created during vm provisioning

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +	// for all the datastores passed in generate the template name and delete it
->
  // find and delete vm-templates from all provided datastores

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +		template := createTemplateName(vm.Template, datastore)
// generate template name <provided-name-<datastore name>

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +		// finds the template vm
// find all vm-templates in data-centre with matching name

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +			// adds the template name if it doesn't exist or in case of error
// add to missing templates list, if it doesn't exist or in case of error

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +		temp, err := findVM(vm, dcMo, template)
rename "temp" to something intuitive

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +		// creates the vm object and calls destroy function on the vm
// create vm object for found vm-template and calls destroy function on the vm

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +			templates = append(templates, template)
"templates" -> "missingTemplates"

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +	// if length of templates > 0 return as error else return nill as error
// If there are any missing templates, return error

2017-02-21 07:15 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +		return fmt.Errorf("[ %s ] templates not found.", strings.Join(templates, ", "))
Mention that although operation has failed. Some template might get deleted.
e.g.
"Following template are not found:
 [<list of missing templates>]
However, any found templates are deleted."

2017-02-21 09:08 UTC, avnish30jn commented
Incorporated all pr comments.
Jira ticket for "template name generation" logic

C3-136

2017-02-21 10:48 UTC, pankajtandon12 approved these changes
LGTM

2017-02-21 10:48 UTC, pankajtandon12 commented on virtualmachine/vsphere/vm.go
> +		return fmt.Errorf("Following templates not found [ %s ]. However any found templates are deleted", strings.Join(missingTemplates, ", "))
use newline "\n"

2017-02-21 12:22 UTC, merged