MRPHS-3917: Libretto changes for adding support for Multi-VM operation in Halo for Vsphere
apporbit/libretto pull request #76
Opened 2018-01-03 08:55 UTC by nirav1007

**Jira Id**

[MRPHS-3917](https://apporbit.atlassian.net/browse/MRPHS-3917)

**Problem**

To support multi-vm operations through Halo some structs and parameters needs to changed.

**Resolution**

Three changes have been done:

1. SkipExisting parameter type has been changed from int to *int. Because, now request will be directly unmarshaled into struct, it needs to be checked if actually this parameter was in request or not else we need to set default value for this.

2. Flavor struct is modified to include Name. This is done so that all related to Flavor whether its name or configuration in terms of CPUs and Memory can be received in single unit.

3. NetworkSettings is changed to NetworkSetting because for single vm its appropriate to name it NetworkSetting as it represents single settings and then we can use NetworkSettings name for group of vms in request.

**Testing**

Unit tested all the multi-vm operations with dummy client. Logs attached.
[c3.log](https://github.com/apporbit/libretto/files/1520627/c3.log)

**Note:**
This change will require change in Halo and Appos(C3ntry).
PR for Halo: [MRPHS-3917](https://github.com/apporbit/halo/pull/65)
PR for Appos(C3ntry):  [MRPHS-3920](https://github.com/apporbit/appos/pull/281)

2018-01-03 09:06 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +			switch *vm.SkipExisting {
Check if SkipExisting  is nil or not.

2018-01-03 09:12 UTC, avnish30jn requested changes

2018-01-03 09:12 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +			switch *vm.SkipExisting {
Check if SkipExisting  is nil or not.

2018-01-03 09:12 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +func (vm *VM) GetIPsAndIds() ([]net.IP, string, string, error) {
We are returning too many values here, should we use existing structures here. 
For eg: VMInfo

2018-01-04 10:05 UTC, pankajtandon12 approved these changes

2018-01-04 10:12 UTC, avnish30jn approved these changes
LGTM

2018-01-04 11:41 UTC, merged