MRPHS-3918: Updated AddDisk to send appropriate err in case of failure and RemoveDisk to use DiskName
apporbit/libretto pull request #77
Opened 2018-01-03 09:04 UTC by nirav1007

**Jira Id**

[MRPHS-3917](https://apporbit.atlassian.net/browse/MRPHS-3918)

**Problem**

Currently AddDisk just returns error without any information of index or name of disk for which it occur in case of failure. So there is not information of how many disks are created from a given list.
RemoveDisk receives list of vmdk files names as separate parameter, though we have DiskName parameter in Disk struct which is used to store vmdk file name.

**Resolution**

reconfigureVM is modified to return err with appropriate disk index and its values for which it occured and also returns updated vm struct with updated disk information so that how many disks are created before failure can be seen.

RemoveDisk is updated to use DiskName parameter of Disk struct instead of separate list of vmdk file names.

**Testing**

Unit tested all the AddDisk and RemoveDisk operations with dummy client. Logs attached.
[c3_add_delete_volume.log](https://github.com/apporbit/libretto/files/1521080/c3_add_delete_volume.log)

**Note:**
This change will require change in Halo and Appos(C3ntry).
PR for Halo: [MRPHS-3918](https://github.com/apporbit/halo/pull/65)
PR for Appos(C3ntry):  [MRPHS-3920](https://github.com/apporbit/appos/pull/281)

2018-01-03 09:30 UTC, avnish30jn requested changes

2018-01-03 09:30 UTC, avnish30jn commented on virtualmachine/vsphere/util.go
> +		vmdkFilename := diffDisks(devListAfter, devListBefore)
Please check if  `devListBefore` can be removed and `devices` can be used here.

2018-01-03 09:30 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +				if strings.HasSuffix(fileName, disk.DiskName) {
if `disk.DiskName` is empty, HasSuffix will return true and the first disk will be removed. Change this to `fileName == disk.DiskName`.

2018-01-03 10:36 UTC, nirav1007 commented on virtualmachine/vsphere/util.go
> +		vmdkFilename := diffDisks(devListAfter, devListBefore)
Have reduced span & one call for devListBefore and reusing devices variable for devListAfter.

2018-01-04 10:14 UTC, pankajtandon12 approved these changes

2018-01-04 10:42 UTC, avnish30jn approved these changes
LGTM

2018-01-04 11:55 UTC, merged