MRPHS-4596: Add custom field to Visor images during creation and add GetVisorList call
apporbit/libretto pull request #83
Opened 2018-01-16 09:49 UTC by nirav1007

**Jira Id**

[MRPHS-4596](https://apporbit.atlassian.net/browse/MRPHS-4596)

**Problem**
Currently there is no difference between visor templates(created through/for AppOrbit) and normal templates. There should be a way to identify visor templates and provide a get call for listing them.

**Resolution**
-  Updated ConvertToTemplate call to add custom field to visor which is created
- Updated GetVmList call to used custom field to distinguish visor templates from other templates and return only those when asked 

**Testing**
Unit tested ConvertToTemplate and GetVisorList functions with Halo dummy client. Logs attached.
[c3_4596.log](https://github.com/apporbit/libretto/files/1634450/c3_4596.log)

2018-01-31 12:37 UTC, deepali-gunwant commented on virtualmachine/vsphere/util.go
> +		if err.Error() == "key name not found" {
use this one ErrKeyNameNotFound

2018-02-01 08:10 UTC, avnish30jn requested changes

2018-02-01 08:10 UTC, avnish30jn commented on virtualmachine/vsphere/util.go
> +		if err.Error() == "key name not found" {
Check ErrorObjectNotFound struct.
https://github.com/apporbit/libretto/blob/master/virtualmachine/vsphere/util.go#L73

2018-02-01 08:10 UTC, avnish30jn commented on virtualmachine/vsphere/util.go
> +	key, err = fieldsManager.FindKey(vm.ctx, fieldName)
why are we fetching the key twice? Please check we can use the key returned by Add method.

2018-02-01 08:10 UTC, avnish30jn commented on virtualmachine/vsphere/util.go
> +			_, err := fieldsManager.Add(vm.ctx, fieldName, "VirtualMachine",
Take object type, 'VirtualMachine' also as argument.

2018-02-01 08:10 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +			if VISOR_VALUE == value.(*types.CustomFieldStringValue).Value {
this might panic if value is not of the desired type

2018-02-01 08:10 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +	setCustomField(vm, vmMo, VISOR_FIELD, VISOR_VALUE)
do we need to handle the error here ?

2018-02-01 08:11 UTC, avnish30jn commented on virtualmachine/vsphere/util.go
> +		if err.Error() == "key name not found" {
```go
	if err != nil {
		if _, ok := err.(ErrorObjectNotFound); ok {
			return false, nil
		}
		return false, err
	}
```

2018-02-01 08:12 UTC, avnish30jn commented on virtualmachine/vsphere/vm.go
> +		key, err = fieldsManager.FindKey(vm.ctx, VISOR_FIELD)
fetching key twice, same as above.

2018-02-02 11:41 UTC, avnish30jn approved these changes
LGTM

2018-02-05 09:59 UTC, merged